services:
  - type: web
    name: restaurant-menu-system
    env: python
    region: oregon
    plan: free
    branch: main
    autoDeploy: true

    buildCommand: |
      pip install --upgrade pip wheel setuptools
      pip install --only-binary=:all: Pillow==10.3.0
      pip install -r requirements.txt

    startCommand: gunicorn app:app

    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: PORT
        value: 10000
      - key: FLASK_ENV
        value: production
      - key: FLASK_DEBUG
        value: 0
      - key: SECRET_KEY
        generateValue: true
      - key: SQLALCHEMY_DATABASE_URI
        value: sqlite:///database.db
      - key: SQLALCHEMY_TRACK_MODIFICATIONS
        value: False
      - key: TZ
        value: America/Managua
      - key: LOG_LEVEL
        value: INFO
